### PR TITLE
PMM-352 added Berksfile.lock, as well as using the right version of zookeeper

### PR DESCRIPTION
**Pull request by chenkirk**
@mygit98040 code review

JIRA: http://jira.internal.g2llc.com/browse/PMM-352

### CODE REVIEW

**Comment by mygit98040** [comment]
Not sure you want to check-in Bersfile.lock. I was advised (Peter) not to include it, in fact I deleted it from chef-g2-emr: https://github.com/g2webservices/chef-g2-emr/commit/c01ca3c25ab478d4a2863306ac39fa7554d9450e
and chef-g2-ccs-merchant-etl: https://github.com/g2webservices/chef-g2-ccs-merchant-etl/commit/1bd72051f5557fd443637ab001362e2646a20858

I believe the main reasons is that it will become maintenance burden, because you need to update this file (berks update) whenever you make version changes to any of the cookbook dependencies.

**Comment by chenkirk** [comment]
Hm. It seems then it is a tradeoff between maintenance work versus stability of the same version deployed on all your nodes.

I noticed we have it in https://github.com/g2webservices/chef-g2application-ruby. It is a bit tedious to always remember to check in the lock file. At the same time, it is great to have the exact version deployed. I don't think I have a huge preference towards either direction. My only preference is we should establish consistency across our chef repos (either we take it out of all of them, or keep it in all of them).

Think we should involve some other devs in the conversation?

**Comment by mygit98040** [comment]
I guess it also depends how the cookbook is designed. I don't know chef well enough to know if it is possible to have exact same version w/o the lock file.

**Comment by chenkirk** [comment]
It depends how you specify it in the Berksfile. Let me ask other devs/netops how they feel about it in flowdock

**Pull request merged**
